apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: timesheet-platform
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:

      - job_name: "prometheus"
        static_configs:
          - targets:
              - "localhost:9090"

      - job_name: "timesheet"
        metrics_path: /timesheet-devops/actuator/prometheus
        static_configs:
          - targets:
              - "timesheet:8082"
